"""Pure, standard-library-only ATHB numerical core."""

from .athb_engine import (
    FORMULATION_ID,
    NUMERICAL_CONTRACT_VERSION,
    evaluate_athb,
    relative_air_speed,
)
from .contracts import (
    AUTOMATIC_CLOTHING,
    ApplicabilityReason,
    AthbInputs,
    AthbResult,
    AthbSuccess,
    AutomaticClothing,
    FixedClothing,
    NumericalFailure,
    NumericalFailureCode,
)
from .psychrometrics import (
    CandidateHumidity,
    DewPointResult,
    HumidityRatio,
    MoistureFailure,
    MoistureState,
    candidate_relative_humidity,
    dew_or_frost_point,
    humidity_ratio,
    moisture_state,
    saturation_vapor_pressure_pa,
)
from .radiant import (
    DirectRadiantModel,
    GlobeRadiantModel,
    RadiantFailure,
    RadiantValue,
    SurfaceCompositeRadiantModel,
    SurfaceContribution,
    UniformRadiantModel,
    globe_mean_radiant_temperature,
)

__all__ = [
    "AUTOMATIC_CLOTHING",
    "FORMULATION_ID",
    "NUMERICAL_CONTRACT_VERSION",
    "ApplicabilityReason",
    "AthbInputs",
    "AthbResult",
    "AthbSuccess",
    "AutomaticClothing",
    "CandidateHumidity",
    "DewPointResult",
    "DirectRadiantModel",
    "FixedClothing",
    "GlobeRadiantModel",
    "HumidityRatio",
    "MoistureFailure",
    "MoistureState",
    "NumericalFailure",
    "NumericalFailureCode",
    "RadiantFailure",
    "RadiantValue",
    "SurfaceCompositeRadiantModel",
    "SurfaceContribution",
    "UniformRadiantModel",
    "candidate_relative_humidity",
    "dew_or_frost_point",
    "evaluate_athb",
    "globe_mean_radiant_temperature",
    "humidity_ratio",
    "moisture_state",
    "relative_air_speed",
    "saturation_vapor_pressure_pa",
]
